# Generated by Django 2.2.4 on 2021-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaAdmin', '0002_auto_20210603_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
