# Generated by Django 2.2.4 on 2021-06-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaAdmin', '0003_transaccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
