# Generated by Django 2.2.4 on 2021-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaAdmin', '0004_auto_20210608_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
