# Generated by Django 2.2.4 on 2021-02-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInciden', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCate', models.CharField(max_length=30)),
                ('vidrio', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300, null=True)),
                ('archivado', models.BooleanField(default=False)),
                ('naturaleza', models.BooleanField(default=False)),
                ('final', models.BooleanField(default=False)),
                ('aunEnCocina', models.BooleanField(default=True)),
                ('impreso', models.BooleanField(default=False)),
                ('fkMesero', models.CharField(blank=True, max_length=30, null=True)),
                ('fkCajero', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('modificado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('fechaCuenta', models.DateTimeField(auto_now=True)),
                ('fkCategoriaIncidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.CategoriaIncidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIns', models.CharField(default=' ', max_length=30)),
                ('cantPaquete', models.IntegerField(default=0)),
                ('proveedor', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('fkInsumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumos', models.ManyToManyField(to='cajaCuenta.LineaDeReceta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fkCategoriaProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.CategoriaProducto')),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exito', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('display', models.BooleanField(default=False)),
                ('prioridad', models.BooleanField(default=False)),
                ('paraLlevar', models.BooleanField(default=False)),
                ('modificado', models.BooleanField(default=False)),
                ('fkMesero', models.CharField(blank=True, max_length=30, null=True)),
                ('comentariomod', models.CharField(blank=True, max_length=300, null=True)),
                ('enCocina', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=140, null=True)),
                ('horaPedido', models.TimeField(auto_now=True)),
                ('fkCategoriaIncidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.CategoriaIncidencia')),
                ('fkCuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='LineaDePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('cebolla', models.IntegerField(default=0, null=True)),
                ('fkPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Pedido')),
                ('fkProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fkInsumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Insumo')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fkMesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cajaCuenta.Mesa'),
        ),
    ]
