# Generated by Django 2.2.4 on 2021-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0002_auto_20210428_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadepedido',
            name='aguacate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='aguacate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='cebolla',
            field=models.BooleanField(default=False),
        ),
    ]
