# Generated by Django 2.2.4 on 2021-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0005_auto_20210501_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cebollaBase',
            field=models.BooleanField(default=False),
        ),
    ]
