# Generated by Django 2.2.4 on 2021-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0006_producto_cebollabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cebollaBase',
        ),
        migrations.AddField(
            model_name='lineadepedido',
            name='cebollaBase',
            field=models.BooleanField(default=False),
        ),
    ]
