# Generated by Django 2.2.4 on 2021-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0007_auto_20210501_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadepedido',
            name='cebollaBase',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
