# Generated by Django 2.2.4 on 2021-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0008_auto_20210501_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='paquete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantPaquete',
            field=models.IntegerField(default=1),
        ),
    ]
