# Generated by Django 2.2.4 on 2021-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0009_auto_20210513_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tyh',
            field=models.BooleanField(default=False),
        ),
    ]
