# Generated by Django 2.2.4 on 2021-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0010_pedido_tyh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='telefono',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
