# Generated by Django 2.2.4 on 2021-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0011_cuenta_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='telefono',
            new_name='c',
        ),
    ]
