# Generated by Django 2.2.4 on 2021-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0012_auto_20210514_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='c',
            new_name='telefono',
        ),
    ]
