# Generated by Django 2.2.4 on 2021-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0013_auto_20210514_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
