# Generated by Django 2.2.4 on 2021-05-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0014_cuenta_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadepedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineadepedido',
            name='modificado',
            field=models.BooleanField(default=False),
        ),
    ]
