# Generated by Django 2.2.4 on 2021-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0015_auto_20210523_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadepedido',
            name='comentarioMod',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
