# Generated by Django 2.2.4 on 2021-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0016_lineadepedido_comentariomod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadepedido',
            name='comentarioMod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
