# Generated by Django 2.2.4 on 2021-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0019_auto_20210601_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCuenta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaPedido',
            field=models.TimeField(),
        ),
    ]
