# Generated by Django 2.2.4 on 2021-06-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0020_auto_20210602_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCuenta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaPedido',
            field=models.TimeField(null=True),
        ),
    ]
