# Generated by Django 2.2.4 on 2021-06-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0021_auto_20210602_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCuenta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaPedido',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
