# Generated by Django 2.2.4 on 2021-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0022_auto_20210602_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='horaCuenta',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCuenta',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
