# Generated by Django 2.2.4 on 2021-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0023_producto_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
