# Generated by Django 2.2.4 on 2021-06-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0024_auto_20210608_1242'),
        ('cajaCuenta', '0023_auto_20210608_1207'),
    ]

    operations = [
    ]
