# Generated by Django 2.2.4 on 2021-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0025_merge_20210608_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, upload_to='cajaCuenta'),
        ),
    ]
