# Generated by Django 2.2.4 on 2021-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0029_auto_20210711_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='vidrio',
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='cocinaNormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='comidaMexicana',
            field=models.BooleanField(default=False),
        ),
    ]
