# Generated by Django 2.2.4 on 2021-07-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaCuenta', '0030_auto_20210712_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mex',
            field=models.BooleanField(default=False),
        ),
    ]
